### ISSUE TITLE
Issue when reading a column of type "N" length 6

### ISSUE THREAD

**Issue by siliconxp** [yellowfeather/DbfDataReader#17]
Great work. Thanks

I faced an issue while reading a file that had a column type "N" with length 6.
=============
Unhandled Exception: System.ArgumentException: The output char buffer is too small to contain the decoded characters, encoding 'Unicode (UTF-8)' fallback 'System.Text.DecoderReplacementFallback'.
Parameter name: chars
   at System.Text.Encoding.ThrowCharsOverflow()
   at System.Text.Encoding.ThrowCharsOverflow(DecoderNLS decoder, Boolean nothingDecoded)
   at System.Text.UTF8Encoding.GetChars(Byte* bytes, Int32 byteCount, Char* chars, Int32 charCount, DecoderNLS baseDecoder)
   at System.Text.DecoderNLS.GetChars(Byte[] bytes, Int32 byteIndex, Int32 byteCount, Char[] chars, Int32 charIndex, Boolean flush)
   at System.Text.DecoderNLS.GetChars(Byte[] bytes, Int32 byteIndex, Int32 byteCount, Char[] chars, Int32 charIndex)
   at System.IO.BinaryReader.InternalReadOneChar()
   at System.IO.BinaryReader.PeekChar()
   at DbfDataReader.DbfValueLong.Read(BinaryReader binaryReader)
   at DbfDataReader.DbfRecord.Read(BinaryReader binaryReader)
   at db.Program.Main(String[] args) in C:\....\Program.cs:line 60

**Comment by chrisrichards** [comment]
Are you able to supply a file for testing?

**Comment by chrisrichards** [comment]
Closing as there have been quite a few changes since this issue was raised and I believe columns are being read OK. Happy to reopen if the problem still exists and you can supply a file for testing. Thanks.
